<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Tuesday, October 7, 2025 3:00:36 PM</msg><msg code="1" type="100">﻿Traceback (most recent call last):
﻿  File "&lt;string&gt;", line 80, in execute
﻿  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 235, in SetProgressor
﻿    return gp.setProgressor(type, message, min_range, max_range, step_value)
﻿           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 113, in setProgressor
﻿    self._gp.SetProgressor(*gp_fixargs(args, True)))
﻿    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿AttributeError: Object: Error in parsing arguments for SetProgressor
</msg><msg code="-2147467259" type="100">Failed to execute (GraduatedColorsRenderer).</msg><msg code="0" type="3">Failed at Tuesday, October 7, 2025 3:00:37 PM (Elapsed Time: 0.53 seconds)</msg></messages>